modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/McJtyMods/ArienteWorld/issues"
displayURL="http://github.com/McJtyMods/ArienteWorld/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="arienteworld"
version="${file.jarVersion}"
displayName="ArienteWorld"
#updateJSONURL="http://myurl.me/" #optional
description='''
ArienteWorld is based on Ariente and adds a new and alien dimension for
players to explore
'''

[[dependencies.arienteworld]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ariente]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.15-4.1.7,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.ariente]]
    modId="ariente"
    mandatory=true
    versionRange="[1.15-0.0.0,)"
    ordering="AFTER"
    side="BOTH"